server:
  port: 9099

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/salama232/Config-Server
          clone-on-start: true